language: java

os:
  - linux

sudo: required

services:
  - docker

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script: ./gradlew --info --refresh-dependencies clean build
